### ISSUE TITLE
Triangulation error

### ISSUE THREAD

**Issue by fgrosse** [Tchayen/triangolatte#3]
I was looking into using this library for a small side project but I am currently running into an error.

This is a reproducible unit test:
```go
func TestTriangulationError(t *testing.T) {
	vertices := []triangolatte.Point{
		{X: 512.00, Y: 30.00},
		{X: 512.00, Y: 145.04},
		{X: 596.96, Y: 145.04},
		{X: 596.96, Y: 85.05},
		{X: 636.96, Y: 85.05},
		{X: 636.96, Y: 30.00},
		{X: 512.00, Y: 30.00},
	}

	_, err := triangolatte.Polygon(vertices)
	if err != nil {
		t.Fatal(err)
	}
}
```

```
=== RUN   TestTriangulationError
--- FAIL: TestTriangulationError (0.00s)
    shape_test.go:22: oops
FAIL

Process finished with exit code 1
```

I have no experience with doing polygon triangulation so maybe I am doing something stupid? What resources would you recommend to learn more about the algorithm in detail?

**Comment by tchayen** [comment]
Hi!

I drew your example to visualize it for myself and it appears to me that:
- you've put starting point twice (it shouldn't happen)
- you've provided points in reversed order (_counter clock wise_ vs expected _clock wise_)

With those changes in place, the array looks like this:
```go
points = []triangolatte.Point{
		{X: 636.96, Y: 30.00},
		{X: 636.96, Y: 85.05},
		{X: 596.96, Y: 85.05},
		{X: 596.96, Y: 145.04},
		{X: 512.00, Y: 145.04},
		{X: 512.00, Y: 30.00},
	}
```

And the test starts passing :tada:.

You can check if it resembles expected shape using `examples/wireframe` (check its README for info on dependency installation and usage). Here is my result (which looks exactly like the one I've expected):

![screenshot](https://user-images.githubusercontent.com/5769281/57587546-d24c9a80-7506-11e9-8839-06e763c283de.png)

The conclusion for me is that I have to make README and/or docs more descriptive about what the functions expect.

**And to answer the other question:**

I've written a short [blog post](https://tchayen.github.io/triangulation-of-polygons) about it. It might be a bit useful. The linked resources under that one will also be helpful, especially the most popular [paper](https://www.geometrictools.com/Documentation/TriangulationByEarClipping.pdf) on it.

Feel free to ask if you have any more questions feel free to ask them here or on DM on [Twitter](https://twitter.com/tczajecki).

**Comment by fgrosse** [comment]
Thanks for the nice and quick answer :)

> you've put starting point twice (it shouldn't happen)

I actually did this intentionally as I believed the polygon must be closed. Apart from improving the documentation, such an issue could actually be caught easily by adding a simple check at the beginning of in the function which could a more helpful error message. If you want I can also submit a PR for this small addition.

> you've provided points in reversed order (counter clock wise vs expected clock wise)

Ok, good no know. I wonder if your package could handle that as well somehow since the polygon I am trying to triangulate is coming from user input. Alternatively I have to detect the direction in which it is drawn and then reverse the order at the caller.

And lastly thanks for a link to your blog post and a link to the paper. I will study them in detail later this week. I see you actually link to the paper already in your README but not to your blog post. Maybe you want to add it?

Regarding this issue I think it can now be closed but I leave it to you in case you want to track the documentation or handling with this.

**Comment by tchayen** [comment]
I've always seen polygons defined with assumption that the last point and first one are connected. Usually I'd call it input error, but it's true that handling it wouldn't be hard and might come helpful.

Feel free to open PR with it if you want 😃. I'll be very grateful.

Regarding direction of points – detecting it wouldn't be that hard, but it is additional computational cost so I'd rather provide a parameter to specify direction of data.
